name: floodcrops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scipy
  - numpy
  - earthengine-api
  - pandas
  - jupyter
  - geopandas
  - matplotlib
  - seaborn
  - pip
  - contextily
  - rioxarray
  - pytorch
  - pytorch-lightning
  - torchvision
  - wandb
  - torchmetrics
